"""Generate a random number between 1 and 9 (including 1 and 9). Ask the user to guess the number,
then tell them whether they guessed too low, too high, or exactly right.

Extras:
Keep the game going until the user types “exit”
Keep track of how many guesses the user has taken, and when the game ends, print this out."""


import random

systemNumber = random.randint(1, 9)
guess = ''
guessCount = 0
# guessCount += 1

while guess != systemNumber:
    print("A number has been generated by the system. Try and guess it.\n")
    try:
        guess = int(input())
        break
    except ValueError:
        print("This is not a number - start over.")

    if guess > systemNumber:
        print("Your guess is too high.")
    elif guess < systemNumber:
        print("Your guess is too low.")
    else:
        print("Bingo! You got it")  # in", + str(guessCount), + "tries.")
